name: Generate Matrix Snake

on:
  schedule:
    # Tự động chạy mỗi 12 tiếng
    - cron: "0 */12 * * *" 
  
  # Cho phép chạy thủ công bằng tay
  workflow_dispatch:
  
  # Chạy mỗi khi bạn push code lên nhánh main
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Bước tạo file SVG con rắn
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ TranLaiAn }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#00FF41&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Bước đẩy file ảnh lên nhánh 'output' để hiển thị
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
